version: '3.8'
services:
  userservice:
    image: userservice
    container_name: container_userservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - dbuser
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80      

  contactservice:
    image: contactservice
    container_name: container_contactservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - dbcontact
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      
  dbuser:
    image: mysql:8.0
    container_name: container_dbuser
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/

  dbcontact:
    image: mysql:8.0
    container_name: container_dbcontact
    environment:
      MYSQL_DATABASE: contactdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/